version: '2'
services:
  mysql:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - ./db:/var/lib/mysql
  php:
    build: 
      context: ./php
      args:
        WEBROOT: /var/www/homepage
    ports:
      - '127.0.0.1:80:80'
    volumes:
      - ../:/var/www/
    depends_on:
      - mysql
